# Github Action 설정 파일
name: Frontend Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker image
      run: |
        docker build -t rtf-app:latest .
        docker tag rtf-app:latest ${{ secrets.ECR_RTF_REPO }}:latest

    - name: Push Docker image to ECR
      run: |
        docker push ${{ secrets.ECR_RTF_REPO }}:latest

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      id: deploy
      with:
        host: ${{ secrets.HOST }} #EC2 인스턴스의 탄력적 IP
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.KEY }} #EC2 인스턴스 생성 시 생성한 키 페어 .pem 파일 복붙 (begin 부터 end 까지 전체 복붙)
        script: |
          sudo docker rm -f rtf-container
          sudo docker pull ${{ secrets.ECR_RTF_REPO }}:latest
          sudo docker run -d --name rtf-container -p 80:80 ${{ secrets.ECR_RTF_REPO }}:latest